name: Release
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v2

      - name: ✅ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: |
          npm install

      - name: 📘 Run linting
        run: |
          npm run lint

      - name: 🧪 Run tests
        run: |
          npm run test

      - name: 🔨 Run build
        run: |
          npm run build --omit=dev

  Coverage:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: ✅ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: |
          npm install

      - name: 🧪 Run tests
        run: |
          npm run test

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

  Docs:
    name: Push docs to release Branch
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v2

      - name: ✅ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: |
          npm install

      - name: 🧪 Run tests (to generate docs)
        run: |
          npm run test

      - name: 🚀 Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: docs
          folder: ./docs

  Release:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: '0'

      - name: ✅ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 🏷 Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬆️ Update npm package version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{steps.tagging.outputs.tag}}

      - name: ➕ Commit files
        run: |
          git config --local user.email "jan.philip.wahle@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add package.json
          git commit -m "[release-bot] Update npm version"

      - name: 💨 Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.ref }}

      - name: 🔨 Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          generateReleaseNotes: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: 🔑 Docker GitHub package login
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Build docker image
        run: docker build -t ghcr.io/gipplab/cs-insights-backend:${{ steps.tag_version.outputs.new_tag }} -t ghcr.io/gipplab/cs-insights-backend:latest .

      - name: 📦 Push docker image
        run: |
          docker push ghcr.io/gipplab/cs-insights-backend:${{ steps.tag_version.outputs.new_tag }}
          docker push ghcr.io/gipplab/cs-insights-backend:latest
